export * from './Button'
export * from './Heading'
export * from './Svg'
export * from './Text'
export * from './DropDown'
export * from './SwitchButton'
export * from './SettingsPanel'

export { default as Spinner } from './Spinner'
export { default as DepositMenu } from './BurgerMenu/Deposit'
export { default as StakeMenu } from './BurgerMenu/Stake'
export { default as ConnectedWallet } from './ConnectedWallet'
export { default as Menu } from './BurgerMenu'